version: "2.6"
services:
  dts-master:
    image: poormancontainer/poormandtsonce:ghlatest
    container_name: dts-master
    volumes:
      - ${SAVES}:/root/.klei/DoNotStarveTogether
      - ${MODS}:/dts/mods/dedicated_server_mods_setup.lua
    restart: unless-stopped
    command: "./run-master.sh"   
    networks:
      cluster_net:
        ipv4_address: 172.16.238.10
  
  dts-caves:
    image: poormancontainer/poormandtsonce:ghlatest
    container_name: dts-caves
    volumes:
      - ${SAVES}:/root/.klei/DoNotStarveTogether
      - ${MODS}:/dts/mods/dedicated_server_mods_setup.lua
    restart: unless-stopped
    command: "./run-caves.sh"
    networks:
      cluster_net:
        ipv4_address: 172.16.238.11
         
networks:
  cluster_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
